### ISSUE TITLE
Rename plugin name

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-media-analytics#43]
Renaming into BEA - Medialitycs

**Comment by MaximeCulea** [comment]
@herewithme better ? ;)

**Comment by herewithme** [comment]
@MaximeCulea à voir si c'est pas gênant avec cette boite : https://www.linkedin.com/company/medianalytics/?originalSubdomain=fr

**Comment by MaximeCulea** [comment]
@herewithme "BEA - Media analytics" alors, il y aura toujours qqchose :p

**Comment by herewithme** [comment]
j'aime bien, simple & compréhensible !

**Comment by MaximeCulea** [comment]
Done
