### ISSUE TITLE
ACF indexation not supporting 'clone' and 'group' fields type

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-media-analytics#47]
The classes/helper/post.php:80 method don't support 'clone' and 'group' fields type. They should be working same as 'repeater' ones - how the field is structured.
 
Wondering if's not easier to get all fields against one post with `get_fields( $post_id )` and foreach fields, check the type, and then get the value or not.

**Comment by herewithme** [comment]
:ah:

**Comment by MaximeCulea** [comment]
Done.
But could be optimized by saving this acf's "media" fields somewhere (one time) before getting the according post media'ids.

**Comment by MaximeCulea** [comment]
TODO: Unit tests + Documentation (github readme + wp readme)
