### ISSUE TITLE
On plugin update, check versions for forcing indexation

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-media-analytics#50]
Sometimes, when updating the plugin from an older version to a new one, as there are new features added.
It could be usefull to check versions and automatically add a single event launching then the cron for forcing indexation.

**Comment by MaximeCulea** [comment]
This should be our next todo, it's very important, otherwise new code is useless !
@herewithme you agree ?

**Comment by herewithme** [comment]
I think we have to look at search plugins (eg SearchWP) on the notion of indexing, especially the possibility of re-indexing and viewing progress.

**Comment by MaximeCulea** [comment]
About seeing the indexation progress #71.

[] Think about admin notice i18n
[] Test both cases (update + install)
[] Do PR

**Comment by MaximeCulea** [comment]
Done !
