### ISSUE TITLE
Handle ACF Options

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-media-analytics#51]

**Comment by MaximeCulea** [comment]
Maybe create an ACF addon which load post fields and options fields classes

**Comment by herewithme** [comment]
@MaximeCulea This ticket generates multiple problems, table structure, data processing logic of ACF, it must be discussed.

**Comment by herewithme** [comment]
At this point, each media is double counting for option pages.

**Comment by herewithme** [comment]
The last point is resolved, each media have a own counter with option page detail

**Comment by herewithme** [comment]
Add ACF settings pages into WP-CLi command

**Comment by herewithme** [comment]
add support for acf-component-field.gummi.io

**Comment by herewithme** [comment]
PR created : https://github.com/BeAPI/bea-media-analytics/pull/65/

**Comment by MaximeCulea** [comment]
@herewithme #65 merged ! 🙌 
We need some testing now ;)

**Comment by herewithme** [comment]
@MaximeCulea I have a client project that performs a full audit for us;)
