### ISSUE TITLE
Refactor way to register wp cli commands

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/bea-media-analytics#59]
The second wp cli command overwrite the first one.

**Comment by herewithme** [comment]
@MaximeCulea a quick hotfix for allow usage cli command.

**Comment by MaximeCulea** [comment]
I'll refactor tonight !!

**Comment by MaximeCulea** [comment]
@herewithme check it out all commands working as subcommands https://github.com/BeAPI/bea-media-analytics/tree/feature/59#wp-cli. No more actions required.
Good for you ?

**Comment by herewithme** [comment]
everything looks good!
