### ISSUE TITLE
The get_unused_media function deserves an custom SQL query

### ISSUE THREAD

**Issue by herewithme** [BeAPI/bea-media-analytics#60]
The current method works, but it is very consuming in performance.
You can directly retrieve the unrelated media via an SQL query and the associated join.

**Comment by MaximeCulea** [comment]
You mean https://github.com/BeAPI/bea-media-analytics/blob/master/classes/helper/api.php#L16 should deserve a custom query for improving performances ? @herewithme

**Comment by herewithme** [comment]
@MaximeCulea yes. (code sample https://github.com/BeAPI/bea-content-sync-fusion/blob/master/classes/query.php)

**Comment by herewithme** [comment]
Proposition : https://github.com/BeAPI/bea-media-analytics/pull/61
